name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        repository: danielga/garrysmod_common
        ref: x86-64-support-sourcesdk
        path: 'garrysmod_common'
    - name: Install Premake
      run: |
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz -O premake.tar.gz
        tar -xvf premake.tar.gz
        chmod +x premake5
        sudo cp premake5 /usr/bin
        sudo apt-get update
        sudo apt-get install g++-multilib
        gcc --version
    - name: Generate Project
      run: |
        premake5 --gmcommon=garrysmod_common gmake
    - name: Make
      run: |
        cd projects/linux/gmake
        make
        make config=releasewithsymbols_x86_64
    - uses: actions/upload-artifact@v2
      with:
        name: gmsv_eightbit_linux.dll
        path: projects/linux/gmake/x86/ReleaseWithSymbols/gmsv_eightbit_linux.dll
    - uses: actions/upload-artifact@v2
      with:
        name: gmsv_eightbit_linux64.dll
        path: projects/linux/gmake/x86_64/ReleaseWithSymbols/gmsv_eightbit_linux64.dll
  build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        repository: danielga/garrysmod_common
        path: 'garrysmod_common'
        ref: x86-64-support-sourcesdk
    - name: Install Premake
      run: |
         curl -L https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip -o premake.zip
         tar -xf premake.zip
    - name: Generate Project
      run: |
        ./premake5.exe --gmcommon=garrysmod_common vs2019
    - name: Build
      run: |
        cd projects/windows/vs2019
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" /p:Configuration=ReleaseWithSymbols /p:Platform=Win32 eightbit.sln
    - uses: actions/upload-artifact@v2
      with:
        name: gmsv_eightbit_windows.dll
        path: projects/windows/vs2019/x86/ReleaseWithSymbols/gmsv_eightbit_win32.dll
    - name: Build 64
      run: |
        cd projects/windows/vs2019
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" /p:Configuration=ReleaseWithSymbols /p:Platform=x64 eightbit.sln
    - uses: actions/upload-artifact@v2
      with:
        name: gmsv_eightbit_win64.dll
        path: projects/windows/vs2019/x86_64/ReleaseWithSymbols/gmsv_eightbit_win64.dll

