name: Build

on:
  push:
    branches: [ master ]
    
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        repository: danielga/garrysmod_common
        ref: master
        path: 'garrysmod_common'
    - name: Install Premake
      run: |
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-linux.tar.gz -O premake.tar.gz
        sudo tar -xvf premake.tar.gz --directory=/usr/bin
        sudo apt-get install g++-multilib
    - name: Generate Project
      run: |
        premake5 --gmcommon=garrysmod_common gmake
    - name: Make
      run: |
        cd projects/linux/gmake
        make
    - uses: actions/upload-artifact@v2
      with:
        name: gmsv_eightbit_linux.dll
        path: projects/linux/gmake/x86/ReleaseWithSymbols/gmsv_eightbit_linux.dll
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        repository: danielga/garrysmod_common
        ref: master
        path: 'garrysmod_common'
    - name: Install Premake
      run: |
         curl -L https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-windows.zip -o premake.zip
         tar -xf premake.zip
    - name: Generate Project
      run: |
        ./premake5.exe --gmcommon=garrysmod_common vs2019
    - name: Build
      run: |
        cd projects/windows/vs2019
        & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" /p:Configuration=ReleaseWithSymbols /p:Platform=Win32 eightbit.sln
    - uses: actions/upload-artifact@v2
      with:
        name: gmsv_eightbit_windows.dll
        path: projects/windows/vs2019/x86/ReleaseWithSymbols/gmsv_eightbit_win32.dll
         
